name: Coverage
on:
  push:
    branches:
      - dev
      - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-python@main
      with:
        python-version: "3.11"
        architecture: x64
    - run: pip install uv
    - run: uv pip install --system .
    - run: uv pip install --system nox
    - run: nox -f noxfile_cov.py -p "3.11"
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
