name: Lint
on:
  push:
    branches:
      - dev
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: "3.11"
        architecture: x64
    - run: pip install nox
    - run: nox -p "3.11" -f noxfile_lint.py
