name: Tests
on:
  push:
    branches:
      - dev
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    name: Python ${{ matrix.python }}
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python }}
        architecture: x64
    - run: pip install uv
    - run: uv pip install nox
    - run: nox -p ${{ matrix.python }}
